version: build{build}

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Release


before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore dotnet\Gherkin.CSharp.sln

  
build:
  publish_nuget: true  
